#!/usr/bin/env python3
"""Generate packed-port SV adapter for 4x4 CMRMeshNoC (no top ports)."""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "async_noc16_mesh_port_adapter.sv"
FLIT_W = 28
NUM_CORES = 16


def emit_module() -> str:
    ports: list[str] = []
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_inputs_{core}_HS_Req(in_req[{core}]), "
            f".io_core_inputs_{core}_HS_Ack(in_ack[{core}]), "
            f".io_core_inputs_{core}_Data_flit(in_data[{core}*FLIT_W +: FLIT_W])"
        )
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_outputs_{core}_HS_Req(out_req[{core}]), "
            f".io_core_outputs_{core}_HS_Ack(out_ack[{core}]), "
            f".io_core_outputs_{core}_Data_flit(out_data[{core}*FLIT_W +: FLIT_W])"
        )
    return "\n".join(
        [
            "module async_noc16_port_adapter_top0 #(",
            f"  parameter integer FLIT_W = {FLIT_W},",
            f"  parameter integer NUM_PORTS = {NUM_CORES}",
            ") (",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_req,",
            "  output wire [NUM_PORTS-1:0]      in_ack,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_req,",
            "  input  wire [NUM_PORTS-1:0]      out_ack,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  wire unused_clock = 1'b0;",
            "  CMRMeshNoC dut (",
            "    .clock(unused_clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
        ]
    )


def main() -> None:
    body = "\n".join(
        [
            "`timescale 1ns/1ps",
            "`default_nettype none",
            "",
            "// Simulation harness adapter for 4x4 CMRMeshNoC.  Packed vectors",
            "// match tb_noc64_async_boundary with NUM_CORES=16 TOP_LANES=0.",
            "// Generated by sim/AsyncNoC/testbench/gen_noc16_mesh_port_adapter.py.",
            "",
            emit_module(),
            "",
            "`default_nettype wire",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
