#!/usr/bin/env python3
"""Generate packed-port SV adapters for NoC_64nodes (top=8 and top=2)."""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "async_noc64_port_adapter.sv"
FLIT_W = 28
NUM_CORES = 64


def emit_module(top_lanes: int) -> str:
    num_ports = NUM_CORES + top_lanes
    ports: list[str] = []
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_inputs_{core}_HS_Req(in_req[{core}]), "
            f".io_core_inputs_{core}_HS_Ack(in_ack[{core}]), "
            f".io_core_inputs_{core}_Data_flit(in_data[{core}*FLIT_W +: FLIT_W])"
        )
    for lane in range(top_lanes):
        phys = NUM_CORES + lane
        ports.append(
            f"    .io_top_input_{lane}_HS_Req(in_req[{phys}]), "
            f".io_top_input_{lane}_HS_Ack(in_ack[{phys}]), "
            f".io_top_input_{lane}_Data_flit(in_data[{phys}*FLIT_W +: FLIT_W])"
        )
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_outputs_{core}_HS_Req(out_req[{core}]), "
            f".io_core_outputs_{core}_HS_Ack(out_ack[{core}]), "
            f".io_core_outputs_{core}_Data_flit(out_data[{core}*FLIT_W +: FLIT_W])"
        )
    for lane in range(top_lanes):
        phys = NUM_CORES + lane
        ports.append(
            f"    .io_top_output_{lane}_HS_Req(out_req[{phys}]), "
            f".io_top_output_{lane}_HS_Ack(out_ack[{phys}]), "
            f".io_top_output_{lane}_Data_flit(out_data[{phys}*FLIT_W +: FLIT_W])"
        )
    return "\n".join(
        [
            f"module async_noc64_port_adapter_top{top_lanes} #(",
            f"  parameter integer FLIT_W = {FLIT_W},",
            f"  parameter integer NUM_PORTS = {num_ports}",
            ") (",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_req,",
            "  output wire [NUM_PORTS-1:0]      in_ack,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_req,",
            "  input  wire [NUM_PORTS-1:0]      out_ack,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  wire unused_clock = 1'b0;",
            "  NoC_64nodes dut (",
            "    .clock(unused_clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
        ]
    )


def main() -> None:
    body = "\n".join(
        [
            "`timescale 1ns/1ps",
            "`default_nettype none",
            "",
            "// Simulation harness adapters for NoC_64nodes.  Packed vectors match",
            "// tb_noc64_async_boundary; the DUT module name stays NoC_64nodes.",
            "// top8 = FatLane1248, top2 = FatLane1222.  Generated by",
            "// sim/AsyncNoC/testbench/gen_noc64_port_adapter.py.",
            "",
            emit_module(8),
            "",
            emit_module(2),
            "",
            "`default_nettype wire",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
