#!/usr/bin/env python3
"""Packed valid/ready adapters for SyncNoC_64nodes.

top1 = Thin (1,1).  top2 = Fat 1-2-2-2.  DUT module name stays SyncNoC_64nodes.
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "sync_noc64_port_adapter.sv"
FLIT_W = 28
NUM_CORES = 64


def emit_module(top_lanes: int) -> str:
    num_ports = NUM_CORES + top_lanes
    ports: list[str] = []
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_inputs_{core}_hs_valid(in_valid[{core}]), "
            f".io_core_inputs_{core}_hs_ready(in_ready[{core}]), "
            f".io_core_inputs_{core}_data_flit(in_data[{core}*FLIT_W +: FLIT_W])"
        )
    for lane in range(top_lanes):
        phys = NUM_CORES + lane
        ports.append(
            f"    .io_top_input_{lane}_hs_valid(in_valid[{phys}]), "
            f".io_top_input_{lane}_hs_ready(in_ready[{phys}]), "
            f".io_top_input_{lane}_data_flit(in_data[{phys}*FLIT_W +: FLIT_W])"
        )
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_outputs_{core}_hs_valid(out_valid[{core}]), "
            f".io_core_outputs_{core}_hs_ready(out_ready[{core}]), "
            f".io_core_outputs_{core}_data_flit(out_data[{core}*FLIT_W +: FLIT_W])"
        )
    for lane in range(top_lanes):
        phys = NUM_CORES + lane
        ports.append(
            f"    .io_top_output_{lane}_hs_valid(out_valid[{phys}]), "
            f".io_top_output_{lane}_hs_ready(out_ready[{phys}]), "
            f".io_top_output_{lane}_data_flit(out_data[{phys}*FLIT_W +: FLIT_W])"
        )
    return "\n".join(
        [
            f"module sync_noc64_port_adapter_top{top_lanes} #(",
            f"  parameter integer FLIT_W = {FLIT_W},",
            f"  parameter integer NUM_PORTS = {num_ports}",
            ") (",
            "  input  wire                      clock,",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_valid,",
            "  output wire [NUM_PORTS-1:0]      in_ready,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_valid,",
            "  input  wire [NUM_PORTS-1:0]      out_ready,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  SyncNoC_64nodes dut (",
            "    .clock(clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
        ]
    )


def main() -> None:
    body = "\n".join(
        [
            "`timescale 1ns/1ps",
            "`default_nettype none",
            "",
            "// Clocked valid/ready harness for SyncNoC_64nodes.",
            "// Packed vectors match tb_noc64_sync_boundary.  Generated by",
            "// sim/AsyncNoC/testbench/gen_sync_noc64_port_adapter.py.",
            "// top1 = Thin (1,1); top2 = Fat 1-2-2-2.",
            "",
            emit_module(1),
            "",
            emit_module(2),
            "",
            "`default_nettype wire",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
