#!/usr/bin/env python3
"""Packed-port adapter for the 2x2 CMRTopMesh (4 tiles x 2 local lanes)."""
from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "async_topmesh2_port_adapter.sv"
FLIT_W = 28
TILES = 4
LANES = 2
NUM_PORTS = TILES * LANES


def main() -> None:
    ports: list[str] = []
    for tile in range(TILES):
        for lane in range(LANES):
            port = tile * LANES + lane
            ports.append(
                "    .io_local_inputs_%d_%d_HS_Req(in_req[%d]), "
                ".io_local_inputs_%d_%d_HS_Ack(in_ack[%d]), "
                ".io_local_inputs_%d_%d_Data_flit(in_data[%d*FLIT_W +: FLIT_W])"
                % (tile, lane, port, tile, lane, port, tile, lane, port)
            )
    for tile in range(TILES):
        for lane in range(LANES):
            port = tile * LANES + lane
            ports.append(
                "    .io_local_outputs_%d_%d_HS_Req(out_req[%d]), "
                ".io_local_outputs_%d_%d_HS_Ack(out_ack[%d]), "
                ".io_local_outputs_%d_%d_Data_flit(out_data[%d*FLIT_W +: FLIT_W])"
                % (tile, lane, port, tile, lane, port, tile, lane, port)
            )
    body = "\n".join(
        [
            "`timescale 1ns/1ps",
            "`default_nettype none",
            "",
            "// Packed handshake adapter for CMRTopMesh 2x2. Generated by",
            "// sim/AsyncNoC/testbench/gen_topmesh2_port_adapter.py.",
            "",
            "module async_topmesh2_port_adapter #(",
            "  parameter integer FLIT_W = %d," % FLIT_W,
            "  parameter integer NUM_PORTS = %d" % NUM_PORTS,
            ") (",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_req,",
            "  output wire [NUM_PORTS-1:0]      in_ack,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_req,",
            "  input  wire [NUM_PORTS-1:0]      out_ack,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  wire unused_clock = 1'b0;",
            "  CMRTopMesh dut (",
            "    .clock(unused_clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
            "",
            "`default_nettype wire",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
