#!/usr/bin/env python3
"""Generate packed-port SV adapters for 256-node async DUTs (PROP clustered + FM)."""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "async_noc256_port_adapter.sv"
FLIT_W = 28
NUM_CORES = 256


def emit_core_ports() -> tuple[list[str], list[str]]:
    ins = []
    outs = []
    for core in range(NUM_CORES):
        ins.append(
            f"    .io_core_inputs_{core}_HS_Req(in_req[{core}]), "
            f".io_core_inputs_{core}_HS_Ack(in_ack[{core}]), "
            f".io_core_inputs_{core}_Data_flit(in_data[{core}*FLIT_W +: FLIT_W])"
        )
        outs.append(
            f"    .io_core_outputs_{core}_HS_Req(out_req[{core}]), "
            f".io_core_outputs_{core}_HS_Ack(out_ack[{core}]), "
            f".io_core_outputs_{core}_Data_flit(out_data[{core}*FLIT_W +: FLIT_W])"
        )
    return ins, outs


def emit_module(name: str, dut: str) -> str:
    ins, outs = emit_core_ports()
    ports = ins + outs
    return "\n".join(
        [
            f"module {name} #(",
            f"  parameter integer FLIT_W = {FLIT_W},",
            f"  parameter integer NUM_PORTS = {NUM_CORES}",
            ") (",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_req,",
            "  output wire [NUM_PORTS-1:0]      in_ack,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_req,",
            "  input  wire [NUM_PORTS-1:0]      out_ack,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  wire unused_clock = 1'b0;",
            f"  {dut} dut (",
            "    .clock(unused_clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
        ]
    )


def main() -> None:
    body = "\n".join(
        [
            "`timescale 1ns/1ps",
            "`default_nettype none",
            "",
            "// 256-core adapters for DATE V3 key-case TB.  No exposed top ports.",
            "// prop = CMRClusteredNoC NoC_256nodes; fm = CMRMeshNoC n=16.",
            "// Generated by sim/AsyncNoC/testbench/gen_noc256_port_adapter.py.",
            "",
            emit_module("async_noc256_port_adapter_prop", "NoC_256nodes"),
            "",
            emit_module("async_noc256_port_adapter_fm", "CMRMeshNoC"),
            "",
            "`default_nettype wire",
            "",
        ]
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(body, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
