#!/usr/bin/env python3
"""Packed-port SystemVerilog adapters for 256- and 1024-node core-only DUTs.

Hierarchical 64-node networks keep the existing top-port adapters.
This generator covers clustered hierarchical and flat-mesh designs that
expose only core handshake ports.
"""
from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "async_noc_scale_port_adapter.sv"
FLIT_W = 28

SPECS = (
    (256, "prop", "NoC_256nodes"),
    (256, "fm", "CMRMeshNoC"),
    (1024, "prop", "NoC_1024nodes"),
    (1024, "fm", "CMRMeshNoC"),
)


def emit_core_ports(num_cores: int) -> tuple[list[str], list[str]]:
    ins = []
    outs = []
    for core in range(num_cores):
        ins.append(
            "    .io_core_inputs_%d_HS_Req(in_req[%d]), "
            ".io_core_inputs_%d_HS_Ack(in_ack[%d]), "
            ".io_core_inputs_%d_Data_flit(in_data[%d*FLIT_W +: FLIT_W])"
            % (core, core, core, core, core, core)
        )
        outs.append(
            "    .io_core_outputs_%d_HS_Req(out_req[%d]), "
            ".io_core_outputs_%d_HS_Ack(out_ack[%d]), "
            ".io_core_outputs_%d_Data_flit(out_data[%d*FLIT_W +: FLIT_W])"
            % (core, core, core, core, core, core)
        )
    return ins, outs


def emit_module(nodes: int, kind: str, dut: str) -> str:
    name = "async_noc_port_adapter_%s_%d" % (kind, nodes)
    ins, outs = emit_core_ports(nodes)
    ports = ins + outs
    return "\n".join(
        [
            "module %s #(" % name,
            "  parameter integer FLIT_W = %d," % FLIT_W,
            "  parameter integer NUM_PORTS = %d" % nodes,
            ") (",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_req,",
            "  output wire [NUM_PORTS-1:0]      in_ack,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_req,",
            "  input  wire [NUM_PORTS-1:0]      out_ack,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  wire unused_clock = 1'b0;",
            "  %s dut (" % dut,
            "    .clock(unused_clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
        ]
    )


def main() -> None:
    chunks = [
        "`timescale 1ns/1ps",
        "`default_nettype none",
        "",
        "// Core-only adapters for 256/1024-node DATE V3.1.0 networks.",
        "// Generated by sim/AsyncNoC/testbench/gen_noc_scale_port_adapter.py.",
        "// Do not edit by hand.",
        "",
    ]
    for nodes, kind, dut in SPECS:
        chunks.append(emit_module(nodes, kind, dut))
        chunks.append("")
    chunks.append("`default_nettype wire")
    chunks.append("")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(chunks), encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
