#!/usr/bin/env python3
"""Generate the packed-port SV adapter for NoC16 Fat 1-2-2 (top=2)."""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
OUT = REPO / "sim" / "AsyncNoC" / "async_noc16_port_adapter_top2.sv"
FLIT_W = 28
NUM_CORES = 16
TOP_LANES = 2
NUM_PORTS = NUM_CORES + TOP_LANES


def main() -> None:
    ports: list[str] = []
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_inputs_{core}_HS_Req(in_req[{core}]), "
            f".io_core_inputs_{core}_HS_Ack(in_ack[{core}]), "
            f".io_core_inputs_{core}_Data_flit(in_data[{core}*FLIT_W +: FLIT_W])"
        )
    for lane in range(TOP_LANES):
        phys = NUM_CORES + lane
        ports.append(
            f"    .io_top_input_{lane}_HS_Req(in_req[{phys}]), "
            f".io_top_input_{lane}_HS_Ack(in_ack[{phys}]), "
            f".io_top_input_{lane}_Data_flit(in_data[{phys}*FLIT_W +: FLIT_W])"
        )
    for core in range(NUM_CORES):
        ports.append(
            f"    .io_core_outputs_{core}_HS_Req(out_req[{core}]), "
            f".io_core_outputs_{core}_HS_Ack(out_ack[{core}]), "
            f".io_core_outputs_{core}_Data_flit(out_data[{core}*FLIT_W +: FLIT_W])"
        )
    for lane in range(TOP_LANES):
        phys = NUM_CORES + lane
        ports.append(
            f"    .io_top_output_{lane}_HS_Req(out_req[{phys}]), "
            f".io_top_output_{lane}_HS_Ack(out_ack[{phys}]), "
            f".io_top_output_{lane}_Data_flit(out_data[{phys}*FLIT_W +: FLIT_W])"
        )
    body = "\n".join(
        [
            "`timescale 1ns/1ps",
            "`default_nettype none",
            "",
            "// 16-core Fat 1-2-2 adapter: two top parent lanes.  Generated by",
            "// sim/AsyncNoC/testbench/gen_noc16_port_adapter_top2.py.",
            "",
            "module async_noc16_port_adapter_top2 #(",
            f"  parameter integer FLIT_W = {FLIT_W},",
            f"  parameter integer NUM_PORTS = {NUM_PORTS}",
            ") (",
            "  input  wire                      reset,",
            "  input  wire [NUM_PORTS-1:0]      in_req,",
            "  output wire [NUM_PORTS-1:0]      in_ack,",
            "  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,",
            "  output wire [NUM_PORTS-1:0]      out_req,",
            "  input  wire [NUM_PORTS-1:0]      out_ack,",
            "  output wire [NUM_PORTS*FLIT_W-1:0] out_data",
            ");",
            "  wire unused_clock = 1'b0;",
            "  NoC_16nodes dut (",
            "    .clock(unused_clock), .reset(reset),",
            ",\n".join(ports),
            "  );",
            "endmodule",
            "",
            "`default_nettype wire",
            "",
        ]
    )
    OUT.write_text(body, encoding="utf-8")
    print(OUT)


if __name__ == "__main__":
    main()
