#!/usr/bin/env python3
"""Write hop-TB port maps for every DATE V3 Router geometry.

The includes are instantiated as `CMRRouter dut (` / `SyncCmrRouter dut (` so
SDF annotate and PrimeTime PX keep the historical `.../dut` strip path.
"""
from __future__ import annotations

from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "hop_binds"

GEOMS = ((1, 1), (1, 2), (2, 2), (2, 4), (4, 8))


def _async_map(child: int, parent: int) -> str:
    lines = ["    .clock(unused_clock)", "    .reset(reset)"]
    for direction in range(4):
        for lane in range(child):
            idx = direction * child + lane
            base = "io_inputs_child_%d_%d" % (direction, lane)
            lines.append("    .%s_HS_Req(tb_in_req[%d])" % (base, idx))
            lines.append("    .%s_HS_Ack(tb_in_ack[%d])" % (base, idx))
            lines.append(
                "    .%s_Data_flit(tb_in_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
            )
    for lane in range(parent):
        idx = 4 * child + lane
        base = "io_inputs_parent_%d" % lane
        lines.append("    .%s_HS_Req(tb_in_req[%d])" % (base, idx))
        lines.append("    .%s_HS_Ack(tb_in_ack[%d])" % (base, idx))
        lines.append(
            "    .%s_Data_flit(tb_in_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
        )
    for direction in range(4):
        for lane in range(child):
            idx = direction * child + lane
            base = "io_outputs_child_%d_%d" % (direction, lane)
            lines.append("    .%s_HS_Req(tb_out_req[%d])" % (base, idx))
            lines.append("    .%s_HS_Ack(tb_out_ack[%d])" % (base, idx))
            lines.append(
                "    .%s_Data_flit(tb_out_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
            )
    for lane in range(parent):
        idx = 4 * child + lane
        base = "io_outputs_parent_%d" % lane
        lines.append("    .%s_HS_Req(tb_out_req[%d])" % (base, idx))
        lines.append("    .%s_HS_Ack(tb_out_ack[%d])" % (base, idx))
        lines.append(
            "    .%s_Data_flit(tb_out_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
        )
    return ",\n".join(lines) + "\n"


def _sync_map(child: int, parent: int) -> str:
    lines = ["    .clock(clock)", "    .reset(reset)"]
    for direction in range(4):
        for lane in range(child):
            idx = direction * child + lane
            base = "io_inputs_child_%d_%d" % (direction, lane)
            lines.append("    .%s_hs_valid(tb_in_valid[%d])" % (base, idx))
            lines.append("    .%s_hs_ready(tb_in_ready[%d])" % (base, idx))
            lines.append(
                "    .%s_data_flit(tb_in_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
            )
    for lane in range(parent):
        idx = 4 * child + lane
        base = "io_inputs_parent_%d" % lane
        lines.append("    .%s_hs_valid(tb_in_valid[%d])" % (base, idx))
        lines.append("    .%s_hs_ready(tb_in_ready[%d])" % (base, idx))
        lines.append(
            "    .%s_data_flit(tb_in_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
        )
    for direction in range(4):
        for lane in range(child):
            idx = direction * child + lane
            base = "io_outputs_child_%d_%d" % (direction, lane)
            lines.append("    .%s_hs_valid(tb_out_valid[%d])" % (base, idx))
            lines.append("    .%s_hs_ready(tb_out_ready[%d])" % (base, idx))
            lines.append(
                "    .%s_data_flit(tb_out_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
            )
    for lane in range(parent):
        idx = 4 * child + lane
        base = "io_outputs_parent_%d" % lane
        lines.append("    .%s_hs_valid(tb_out_valid[%d])" % (base, idx))
        lines.append("    .%s_hs_ready(tb_out_ready[%d])" % (base, idx))
        lines.append(
            "    .%s_data_flit(tb_out_data[%d*FLIT_W +: FLIT_W])" % (base, idx)
        )
    return ",\n".join(lines) + "\n"


def main() -> int:
    OUT.mkdir(parents=True, exist_ok=True)
    banner = (
        "// Generated by gen_cmr_hop_dut_bind.py.  Do not edit by hand.\n"
        "// Instantiated as `DUT dut (` so SDF/PX strip_path stays .../dut.\n"
    )
    for child, parent in GEOMS:
        name = "c%d_p%d" % (child, parent)
        (OUT / ("async_ports_%s.vi" % name)).write_text(
            banner + _async_map(child, parent), encoding="utf-8"
        )
        (OUT / ("sync_ports_%s.vi" % name)).write_text(
            banner + _sync_map(child, parent), encoding="utf-8"
        )
        print("wrote", name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
