`timescale 1ns/1ps
module tb_prop_temp64_lane_monitor;
  reg [2047:0] lane_csv;
  integer fd;
  integer count_1_0_0_0 = 0;
  integer count_1_0_0_1 = 0;
  integer count_1_0_0_2 = 0;
  integer count_1_0_0_3 = 0;
  integer count_1_0_1_0 = 0;
  integer count_1_0_1_1 = 0;
  integer count_1_0_1_2 = 0;
  integer count_1_0_1_3 = 0;
  integer count_1_0_2_0 = 0;
  integer count_1_0_2_1 = 0;
  integer count_1_0_2_2 = 0;
  integer count_1_0_2_3 = 0;
  integer count_1_0_3_0 = 0;
  integer count_1_0_3_1 = 0;
  integer count_1_0_3_2 = 0;
  integer count_1_0_3_3 = 0;
  integer count_1_1_0_0 = 0;
  integer count_1_1_0_1 = 0;
  integer count_1_1_0_2 = 0;
  integer count_1_1_0_3 = 0;
  integer count_1_1_1_0 = 0;
  integer count_1_1_1_1 = 0;
  integer count_1_1_1_2 = 0;
  integer count_1_1_1_3 = 0;
  integer count_1_1_2_0 = 0;
  integer count_1_1_2_1 = 0;
  integer count_1_1_2_2 = 0;
  integer count_1_1_2_3 = 0;
  integer count_1_1_3_0 = 0;
  integer count_1_1_3_1 = 0;
  integer count_1_1_3_2 = 0;
  integer count_1_1_3_3 = 0;
  integer count_1_2_0_0 = 0;
  integer count_1_2_0_1 = 0;
  integer count_1_2_0_2 = 0;
  integer count_1_2_0_3 = 0;
  integer count_1_2_1_0 = 0;
  integer count_1_2_1_1 = 0;
  integer count_1_2_1_2 = 0;
  integer count_1_2_1_3 = 0;
  integer count_1_2_2_0 = 0;
  integer count_1_2_2_1 = 0;
  integer count_1_2_2_2 = 0;
  integer count_1_2_2_3 = 0;
  integer count_1_2_3_0 = 0;
  integer count_1_2_3_1 = 0;
  integer count_1_2_3_2 = 0;
  integer count_1_2_3_3 = 0;
  integer count_1_3_0_0 = 0;
  integer count_1_3_0_1 = 0;
  integer count_1_3_0_2 = 0;
  integer count_1_3_0_3 = 0;
  integer count_1_3_1_0 = 0;
  integer count_1_3_1_1 = 0;
  integer count_1_3_1_2 = 0;
  integer count_1_3_1_3 = 0;
  integer count_1_3_2_0 = 0;
  integer count_1_3_2_1 = 0;
  integer count_1_3_2_2 = 0;
  integer count_1_3_2_3 = 0;
  integer count_1_3_3_0 = 0;
  integer count_1_3_3_1 = 0;
  integer count_1_3_3_2 = 0;
  integer count_1_3_3_3 = 0;
  integer count_2_0_0_0 = 0;
  integer count_2_0_0_1 = 0;
  integer count_2_0_0_2 = 0;
  integer count_2_0_0_3 = 0;
  integer count_2_0_1_0 = 0;
  integer count_2_0_1_1 = 0;
  integer count_2_0_1_2 = 0;
  integer count_2_0_1_3 = 0;
  integer count_2_0_2_0 = 0;
  integer count_2_0_2_1 = 0;
  integer count_2_0_2_2 = 0;
  integer count_2_0_2_3 = 0;
  integer count_2_0_3_0 = 0;
  integer count_2_0_3_1 = 0;
  integer count_2_0_3_2 = 0;
  integer count_2_0_3_3 = 0;
  integer count_2_1_0_0 = 0;
  integer count_2_1_0_1 = 0;
  integer count_2_1_0_2 = 0;
  integer count_2_1_0_3 = 0;
  integer count_2_1_1_0 = 0;
  integer count_2_1_1_1 = 0;
  integer count_2_1_1_2 = 0;
  integer count_2_1_1_3 = 0;
  integer count_2_1_2_0 = 0;
  integer count_2_1_2_1 = 0;
  integer count_2_1_2_2 = 0;
  integer count_2_1_2_3 = 0;
  integer count_2_1_3_0 = 0;
  integer count_2_1_3_1 = 0;
  integer count_2_1_3_2 = 0;
  integer count_2_1_3_3 = 0;
  integer count_2_2_0_0 = 0;
  integer count_2_2_0_1 = 0;
  integer count_2_2_0_2 = 0;
  integer count_2_2_0_3 = 0;
  integer count_2_2_1_0 = 0;
  integer count_2_2_1_1 = 0;
  integer count_2_2_1_2 = 0;
  integer count_2_2_1_3 = 0;
  integer count_2_2_2_0 = 0;
  integer count_2_2_2_1 = 0;
  integer count_2_2_2_2 = 0;
  integer count_2_2_2_3 = 0;
  integer count_2_2_3_0 = 0;
  integer count_2_2_3_1 = 0;
  integer count_2_2_3_2 = 0;
  integer count_2_2_3_3 = 0;
  integer count_2_3_0_0 = 0;
  integer count_2_3_0_1 = 0;
  integer count_2_3_0_2 = 0;
  integer count_2_3_0_3 = 0;
  integer count_2_3_1_0 = 0;
  integer count_2_3_1_1 = 0;
  integer count_2_3_1_2 = 0;
  integer count_2_3_1_3 = 0;
  integer count_2_3_2_0 = 0;
  integer count_2_3_2_1 = 0;
  integer count_2_3_2_2 = 0;
  integer count_2_3_2_3 = 0;
  integer count_2_3_3_0 = 0;
  integer count_2_3_3_1 = 0;
  integer count_2_3_3_2 = 0;
  integer count_2_3_3_3 = 0;
  function automatic in_measurement;
    begin
      in_measurement = (tb_cmr_noc64_async_boundary_failfast.core.running &&
        ($realtime * 1000.0 >= tb_cmr_noc64_async_boundary_failfast.core.measurement_start_ps) &&
        ($realtime * 1000.0 < tb_cmr_noc64_async_boundary_failfast.core.measurement_end_ps));
    end
  endfunction
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_0_HS_Req)) count_1_0_0_0 = count_1_0_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_1_HS_Req)) count_1_0_0_1 = count_1_0_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_2_HS_Req)) count_1_0_0_2 = count_1_0_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i0.io_outputs_parent_3_HS_Req)) count_1_0_0_3 = count_1_0_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_0_HS_Req)) count_1_0_1_0 = count_1_0_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_1_HS_Req)) count_1_0_1_1 = count_1_0_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_2_HS_Req)) count_1_0_1_2 = count_1_0_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i1.io_outputs_parent_3_HS_Req)) count_1_0_1_3 = count_1_0_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_0_HS_Req)) count_1_0_2_0 = count_1_0_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_1_HS_Req)) count_1_0_2_1 = count_1_0_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_2_HS_Req)) count_1_0_2_2 = count_1_0_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i2.io_outputs_parent_3_HS_Req)) count_1_0_2_3 = count_1_0_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_0_HS_Req)) count_1_0_3_0 = count_1_0_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_1_HS_Req)) count_1_0_3_1 = count_1_0_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_2_HS_Req)) count_1_0_3_2 = count_1_0_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q0_i3.io_outputs_parent_3_HS_Req)) count_1_0_3_3 = count_1_0_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_0_HS_Req)) count_1_1_0_0 = count_1_1_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_1_HS_Req)) count_1_1_0_1 = count_1_1_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_2_HS_Req)) count_1_1_0_2 = count_1_1_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i0.io_outputs_parent_3_HS_Req)) count_1_1_0_3 = count_1_1_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_0_HS_Req)) count_1_1_1_0 = count_1_1_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_1_HS_Req)) count_1_1_1_1 = count_1_1_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_2_HS_Req)) count_1_1_1_2 = count_1_1_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i1.io_outputs_parent_3_HS_Req)) count_1_1_1_3 = count_1_1_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_0_HS_Req)) count_1_1_2_0 = count_1_1_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_1_HS_Req)) count_1_1_2_1 = count_1_1_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_2_HS_Req)) count_1_1_2_2 = count_1_1_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i2.io_outputs_parent_3_HS_Req)) count_1_1_2_3 = count_1_1_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_0_HS_Req)) count_1_1_3_0 = count_1_1_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_1_HS_Req)) count_1_1_3_1 = count_1_1_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_2_HS_Req)) count_1_1_3_2 = count_1_1_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q1_i3.io_outputs_parent_3_HS_Req)) count_1_1_3_3 = count_1_1_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_0_HS_Req)) count_1_2_0_0 = count_1_2_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_1_HS_Req)) count_1_2_0_1 = count_1_2_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_2_HS_Req)) count_1_2_0_2 = count_1_2_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i0.io_outputs_parent_3_HS_Req)) count_1_2_0_3 = count_1_2_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_0_HS_Req)) count_1_2_1_0 = count_1_2_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_1_HS_Req)) count_1_2_1_1 = count_1_2_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_2_HS_Req)) count_1_2_1_2 = count_1_2_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i1.io_outputs_parent_3_HS_Req)) count_1_2_1_3 = count_1_2_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_0_HS_Req)) count_1_2_2_0 = count_1_2_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_1_HS_Req)) count_1_2_2_1 = count_1_2_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_2_HS_Req)) count_1_2_2_2 = count_1_2_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i2.io_outputs_parent_3_HS_Req)) count_1_2_2_3 = count_1_2_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_0_HS_Req)) count_1_2_3_0 = count_1_2_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_1_HS_Req)) count_1_2_3_1 = count_1_2_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_2_HS_Req)) count_1_2_3_2 = count_1_2_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q2_i3.io_outputs_parent_3_HS_Req)) count_1_2_3_3 = count_1_2_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_0_HS_Req)) count_1_3_0_0 = count_1_3_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_1_HS_Req)) count_1_3_0_1 = count_1_3_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_2_HS_Req)) count_1_3_0_2 = count_1_3_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i0.io_outputs_parent_3_HS_Req)) count_1_3_0_3 = count_1_3_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_0_HS_Req)) count_1_3_1_0 = count_1_3_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_1_HS_Req)) count_1_3_1_1 = count_1_3_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_2_HS_Req)) count_1_3_1_2 = count_1_3_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i1.io_outputs_parent_3_HS_Req)) count_1_3_1_3 = count_1_3_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_0_HS_Req)) count_1_3_2_0 = count_1_3_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_1_HS_Req)) count_1_3_2_1 = count_1_3_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_2_HS_Req)) count_1_3_2_2 = count_1_3_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i2.io_outputs_parent_3_HS_Req)) count_1_3_2_3 = count_1_3_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_0_HS_Req)) count_1_3_3_0 = count_1_3_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_1_HS_Req)) count_1_3_3_1 = count_1_3_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_2_HS_Req)) count_1_3_3_2 = count_1_3_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL1_q3_i3.io_outputs_parent_3_HS_Req)) count_1_3_3_3 = count_1_3_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_0_HS_Req)) count_2_0_0_0 = count_2_0_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_1_HS_Req)) count_2_0_0_1 = count_2_0_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_2_HS_Req)) count_2_0_0_2 = count_2_0_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k0.io_outputs_parent_3_HS_Req)) count_2_0_0_3 = count_2_0_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_0_HS_Req)) count_2_0_1_0 = count_2_0_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_1_HS_Req)) count_2_0_1_1 = count_2_0_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_2_HS_Req)) count_2_0_1_2 = count_2_0_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k1.io_outputs_parent_3_HS_Req)) count_2_0_1_3 = count_2_0_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_0_HS_Req)) count_2_0_2_0 = count_2_0_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_1_HS_Req)) count_2_0_2_1 = count_2_0_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_2_HS_Req)) count_2_0_2_2 = count_2_0_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k2.io_outputs_parent_3_HS_Req)) count_2_0_2_3 = count_2_0_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_0_HS_Req)) count_2_0_3_0 = count_2_0_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_1_HS_Req)) count_2_0_3_1 = count_2_0_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_2_HS_Req)) count_2_0_3_2 = count_2_0_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q0_k3.io_outputs_parent_3_HS_Req)) count_2_0_3_3 = count_2_0_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_0_HS_Req)) count_2_1_0_0 = count_2_1_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_1_HS_Req)) count_2_1_0_1 = count_2_1_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_2_HS_Req)) count_2_1_0_2 = count_2_1_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k0.io_outputs_parent_3_HS_Req)) count_2_1_0_3 = count_2_1_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_0_HS_Req)) count_2_1_1_0 = count_2_1_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_1_HS_Req)) count_2_1_1_1 = count_2_1_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_2_HS_Req)) count_2_1_1_2 = count_2_1_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k1.io_outputs_parent_3_HS_Req)) count_2_1_1_3 = count_2_1_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_0_HS_Req)) count_2_1_2_0 = count_2_1_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_1_HS_Req)) count_2_1_2_1 = count_2_1_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_2_HS_Req)) count_2_1_2_2 = count_2_1_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k2.io_outputs_parent_3_HS_Req)) count_2_1_2_3 = count_2_1_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_0_HS_Req)) count_2_1_3_0 = count_2_1_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_1_HS_Req)) count_2_1_3_1 = count_2_1_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_2_HS_Req)) count_2_1_3_2 = count_2_1_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q1_k3.io_outputs_parent_3_HS_Req)) count_2_1_3_3 = count_2_1_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_0_HS_Req)) count_2_2_0_0 = count_2_2_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_1_HS_Req)) count_2_2_0_1 = count_2_2_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_2_HS_Req)) count_2_2_0_2 = count_2_2_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k0.io_outputs_parent_3_HS_Req)) count_2_2_0_3 = count_2_2_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_0_HS_Req)) count_2_2_1_0 = count_2_2_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_1_HS_Req)) count_2_2_1_1 = count_2_2_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_2_HS_Req)) count_2_2_1_2 = count_2_2_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k1.io_outputs_parent_3_HS_Req)) count_2_2_1_3 = count_2_2_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_0_HS_Req)) count_2_2_2_0 = count_2_2_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_1_HS_Req)) count_2_2_2_1 = count_2_2_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_2_HS_Req)) count_2_2_2_2 = count_2_2_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k2.io_outputs_parent_3_HS_Req)) count_2_2_2_3 = count_2_2_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_0_HS_Req)) count_2_2_3_0 = count_2_2_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_1_HS_Req)) count_2_2_3_1 = count_2_2_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_2_HS_Req)) count_2_2_3_2 = count_2_2_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q2_k3.io_outputs_parent_3_HS_Req)) count_2_2_3_3 = count_2_2_3_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_0_HS_Req)) count_2_3_0_0 = count_2_3_0_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_1_HS_Req)) count_2_3_0_1 = count_2_3_0_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_2_HS_Req)) count_2_3_0_2 = count_2_3_0_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k0.io_outputs_parent_3_HS_Req)) count_2_3_0_3 = count_2_3_0_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_0_HS_Req)) count_2_3_1_0 = count_2_3_1_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_1_HS_Req)) count_2_3_1_1 = count_2_3_1_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_2_HS_Req)) count_2_3_1_2 = count_2_3_1_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k1.io_outputs_parent_3_HS_Req)) count_2_3_1_3 = count_2_3_1_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_0_HS_Req)) count_2_3_2_0 = count_2_3_2_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_1_HS_Req)) count_2_3_2_1 = count_2_3_2_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_2_HS_Req)) count_2_3_2_2 = count_2_3_2_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k2.io_outputs_parent_3_HS_Req)) count_2_3_2_3 = count_2_3_2_3 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_0_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_0_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_0_HS_Req)) count_2_3_3_0 = count_2_3_3_0 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_1_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_1_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_1_HS_Req)) count_2_3_3_1 = count_2_3_3_1 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_2_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_2_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_2_HS_Req)) count_2_3_3_2 = count_2_3_3_2 + 1;
  always @(tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_3_HS_Ack) if (in_measurement() && (tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_3_HS_Ack === tb_cmr_noc64_async_boundary_failfast.core.g_behavioral_noc_prop_temp.noc.dut.tile.propL2_q3_k3.io_outputs_parent_3_HS_Req)) count_2_3_3_3 = count_2_3_3_3 + 1;
  final begin
    lane_csv = "prop_temp64_lane_counts.csv";
    if ($value$plusargs("LANE_CSV=%s", lane_csv)) ;
    fd = $fopen(lane_csv, "w");
    $fwrite(fd, "level,router,parent_lane,accepted_flits\n");
    $fwrite(fd, "1,0,0,%0d\n", count_1_0_0_0);
    $fwrite(fd, "1,0,1,%0d\n", count_1_0_0_1);
    $fwrite(fd, "1,0,2,%0d\n", count_1_0_0_2);
    $fwrite(fd, "1,0,3,%0d\n", count_1_0_0_3);
    $fwrite(fd, "1,1,0,%0d\n", count_1_0_1_0);
    $fwrite(fd, "1,1,1,%0d\n", count_1_0_1_1);
    $fwrite(fd, "1,1,2,%0d\n", count_1_0_1_2);
    $fwrite(fd, "1,1,3,%0d\n", count_1_0_1_3);
    $fwrite(fd, "1,2,0,%0d\n", count_1_0_2_0);
    $fwrite(fd, "1,2,1,%0d\n", count_1_0_2_1);
    $fwrite(fd, "1,2,2,%0d\n", count_1_0_2_2);
    $fwrite(fd, "1,2,3,%0d\n", count_1_0_2_3);
    $fwrite(fd, "1,3,0,%0d\n", count_1_0_3_0);
    $fwrite(fd, "1,3,1,%0d\n", count_1_0_3_1);
    $fwrite(fd, "1,3,2,%0d\n", count_1_0_3_2);
    $fwrite(fd, "1,3,3,%0d\n", count_1_0_3_3);
    $fwrite(fd, "1,4,0,%0d\n", count_1_1_0_0);
    $fwrite(fd, "1,4,1,%0d\n", count_1_1_0_1);
    $fwrite(fd, "1,4,2,%0d\n", count_1_1_0_2);
    $fwrite(fd, "1,4,3,%0d\n", count_1_1_0_3);
    $fwrite(fd, "1,5,0,%0d\n", count_1_1_1_0);
    $fwrite(fd, "1,5,1,%0d\n", count_1_1_1_1);
    $fwrite(fd, "1,5,2,%0d\n", count_1_1_1_2);
    $fwrite(fd, "1,5,3,%0d\n", count_1_1_1_3);
    $fwrite(fd, "1,6,0,%0d\n", count_1_1_2_0);
    $fwrite(fd, "1,6,1,%0d\n", count_1_1_2_1);
    $fwrite(fd, "1,6,2,%0d\n", count_1_1_2_2);
    $fwrite(fd, "1,6,3,%0d\n", count_1_1_2_3);
    $fwrite(fd, "1,7,0,%0d\n", count_1_1_3_0);
    $fwrite(fd, "1,7,1,%0d\n", count_1_1_3_1);
    $fwrite(fd, "1,7,2,%0d\n", count_1_1_3_2);
    $fwrite(fd, "1,7,3,%0d\n", count_1_1_3_3);
    $fwrite(fd, "1,8,0,%0d\n", count_1_2_0_0);
    $fwrite(fd, "1,8,1,%0d\n", count_1_2_0_1);
    $fwrite(fd, "1,8,2,%0d\n", count_1_2_0_2);
    $fwrite(fd, "1,8,3,%0d\n", count_1_2_0_3);
    $fwrite(fd, "1,9,0,%0d\n", count_1_2_1_0);
    $fwrite(fd, "1,9,1,%0d\n", count_1_2_1_1);
    $fwrite(fd, "1,9,2,%0d\n", count_1_2_1_2);
    $fwrite(fd, "1,9,3,%0d\n", count_1_2_1_3);
    $fwrite(fd, "1,10,0,%0d\n", count_1_2_2_0);
    $fwrite(fd, "1,10,1,%0d\n", count_1_2_2_1);
    $fwrite(fd, "1,10,2,%0d\n", count_1_2_2_2);
    $fwrite(fd, "1,10,3,%0d\n", count_1_2_2_3);
    $fwrite(fd, "1,11,0,%0d\n", count_1_2_3_0);
    $fwrite(fd, "1,11,1,%0d\n", count_1_2_3_1);
    $fwrite(fd, "1,11,2,%0d\n", count_1_2_3_2);
    $fwrite(fd, "1,11,3,%0d\n", count_1_2_3_3);
    $fwrite(fd, "1,12,0,%0d\n", count_1_3_0_0);
    $fwrite(fd, "1,12,1,%0d\n", count_1_3_0_1);
    $fwrite(fd, "1,12,2,%0d\n", count_1_3_0_2);
    $fwrite(fd, "1,12,3,%0d\n", count_1_3_0_3);
    $fwrite(fd, "1,13,0,%0d\n", count_1_3_1_0);
    $fwrite(fd, "1,13,1,%0d\n", count_1_3_1_1);
    $fwrite(fd, "1,13,2,%0d\n", count_1_3_1_2);
    $fwrite(fd, "1,13,3,%0d\n", count_1_3_1_3);
    $fwrite(fd, "1,14,0,%0d\n", count_1_3_2_0);
    $fwrite(fd, "1,14,1,%0d\n", count_1_3_2_1);
    $fwrite(fd, "1,14,2,%0d\n", count_1_3_2_2);
    $fwrite(fd, "1,14,3,%0d\n", count_1_3_2_3);
    $fwrite(fd, "1,15,0,%0d\n", count_1_3_3_0);
    $fwrite(fd, "1,15,1,%0d\n", count_1_3_3_1);
    $fwrite(fd, "1,15,2,%0d\n", count_1_3_3_2);
    $fwrite(fd, "1,15,3,%0d\n", count_1_3_3_3);
    $fwrite(fd, "2,0,0,%0d\n", count_2_0_0_0);
    $fwrite(fd, "2,0,1,%0d\n", count_2_0_0_1);
    $fwrite(fd, "2,0,2,%0d\n", count_2_0_0_2);
    $fwrite(fd, "2,0,3,%0d\n", count_2_0_0_3);
    $fwrite(fd, "2,1,0,%0d\n", count_2_0_1_0);
    $fwrite(fd, "2,1,1,%0d\n", count_2_0_1_1);
    $fwrite(fd, "2,1,2,%0d\n", count_2_0_1_2);
    $fwrite(fd, "2,1,3,%0d\n", count_2_0_1_3);
    $fwrite(fd, "2,2,0,%0d\n", count_2_0_2_0);
    $fwrite(fd, "2,2,1,%0d\n", count_2_0_2_1);
    $fwrite(fd, "2,2,2,%0d\n", count_2_0_2_2);
    $fwrite(fd, "2,2,3,%0d\n", count_2_0_2_3);
    $fwrite(fd, "2,3,0,%0d\n", count_2_0_3_0);
    $fwrite(fd, "2,3,1,%0d\n", count_2_0_3_1);
    $fwrite(fd, "2,3,2,%0d\n", count_2_0_3_2);
    $fwrite(fd, "2,3,3,%0d\n", count_2_0_3_3);
    $fwrite(fd, "2,4,0,%0d\n", count_2_1_0_0);
    $fwrite(fd, "2,4,1,%0d\n", count_2_1_0_1);
    $fwrite(fd, "2,4,2,%0d\n", count_2_1_0_2);
    $fwrite(fd, "2,4,3,%0d\n", count_2_1_0_3);
    $fwrite(fd, "2,5,0,%0d\n", count_2_1_1_0);
    $fwrite(fd, "2,5,1,%0d\n", count_2_1_1_1);
    $fwrite(fd, "2,5,2,%0d\n", count_2_1_1_2);
    $fwrite(fd, "2,5,3,%0d\n", count_2_1_1_3);
    $fwrite(fd, "2,6,0,%0d\n", count_2_1_2_0);
    $fwrite(fd, "2,6,1,%0d\n", count_2_1_2_1);
    $fwrite(fd, "2,6,2,%0d\n", count_2_1_2_2);
    $fwrite(fd, "2,6,3,%0d\n", count_2_1_2_3);
    $fwrite(fd, "2,7,0,%0d\n", count_2_1_3_0);
    $fwrite(fd, "2,7,1,%0d\n", count_2_1_3_1);
    $fwrite(fd, "2,7,2,%0d\n", count_2_1_3_2);
    $fwrite(fd, "2,7,3,%0d\n", count_2_1_3_3);
    $fwrite(fd, "2,8,0,%0d\n", count_2_2_0_0);
    $fwrite(fd, "2,8,1,%0d\n", count_2_2_0_1);
    $fwrite(fd, "2,8,2,%0d\n", count_2_2_0_2);
    $fwrite(fd, "2,8,3,%0d\n", count_2_2_0_3);
    $fwrite(fd, "2,9,0,%0d\n", count_2_2_1_0);
    $fwrite(fd, "2,9,1,%0d\n", count_2_2_1_1);
    $fwrite(fd, "2,9,2,%0d\n", count_2_2_1_2);
    $fwrite(fd, "2,9,3,%0d\n", count_2_2_1_3);
    $fwrite(fd, "2,10,0,%0d\n", count_2_2_2_0);
    $fwrite(fd, "2,10,1,%0d\n", count_2_2_2_1);
    $fwrite(fd, "2,10,2,%0d\n", count_2_2_2_2);
    $fwrite(fd, "2,10,3,%0d\n", count_2_2_2_3);
    $fwrite(fd, "2,11,0,%0d\n", count_2_2_3_0);
    $fwrite(fd, "2,11,1,%0d\n", count_2_2_3_1);
    $fwrite(fd, "2,11,2,%0d\n", count_2_2_3_2);
    $fwrite(fd, "2,11,3,%0d\n", count_2_2_3_3);
    $fwrite(fd, "2,12,0,%0d\n", count_2_3_0_0);
    $fwrite(fd, "2,12,1,%0d\n", count_2_3_0_1);
    $fwrite(fd, "2,12,2,%0d\n", count_2_3_0_2);
    $fwrite(fd, "2,12,3,%0d\n", count_2_3_0_3);
    $fwrite(fd, "2,13,0,%0d\n", count_2_3_1_0);
    $fwrite(fd, "2,13,1,%0d\n", count_2_3_1_1);
    $fwrite(fd, "2,13,2,%0d\n", count_2_3_1_2);
    $fwrite(fd, "2,13,3,%0d\n", count_2_3_1_3);
    $fwrite(fd, "2,14,0,%0d\n", count_2_3_2_0);
    $fwrite(fd, "2,14,1,%0d\n", count_2_3_2_1);
    $fwrite(fd, "2,14,2,%0d\n", count_2_3_2_2);
    $fwrite(fd, "2,14,3,%0d\n", count_2_3_2_3);
    $fwrite(fd, "2,15,0,%0d\n", count_2_3_3_0);
    $fwrite(fd, "2,15,1,%0d\n", count_2_3_3_1);
    $fwrite(fd, "2,15,2,%0d\n", count_2_3_3_2);
    $fwrite(fd, "2,15,3,%0d\n", count_2_3_3_3);
    $fclose(fd);
    $display("CMR_LANE_MONITOR_PASS rows=128 output=%0s", lane_csv);
  end
endmodule
