`timescale 1ns/1ps
`default_nettype none

// 16-core Fat 1-2-2 adapter: two top parent lanes.  Generated by
// sim/AsyncNoC/testbench/gen_noc16_port_adapter_top2.py.

module async_noc16_port_adapter_top2 #(
  parameter integer FLIT_W = 28,
  parameter integer NUM_PORTS = 18
) (
  input  wire                      reset,
  input  wire [NUM_PORTS-1:0]      in_req,
  output wire [NUM_PORTS-1:0]      in_ack,
  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,
  output wire [NUM_PORTS-1:0]      out_req,
  input  wire [NUM_PORTS-1:0]      out_ack,
  output wire [NUM_PORTS*FLIT_W-1:0] out_data
);
  wire unused_clock = 1'b0;
  NoC_16nodes dut (
    .clock(unused_clock), .reset(reset),
    .io_core_inputs_0_HS_Req(in_req[0]), .io_core_inputs_0_HS_Ack(in_ack[0]), .io_core_inputs_0_Data_flit(in_data[0*FLIT_W +: FLIT_W]),
    .io_core_inputs_1_HS_Req(in_req[1]), .io_core_inputs_1_HS_Ack(in_ack[1]), .io_core_inputs_1_Data_flit(in_data[1*FLIT_W +: FLIT_W]),
    .io_core_inputs_2_HS_Req(in_req[2]), .io_core_inputs_2_HS_Ack(in_ack[2]), .io_core_inputs_2_Data_flit(in_data[2*FLIT_W +: FLIT_W]),
    .io_core_inputs_3_HS_Req(in_req[3]), .io_core_inputs_3_HS_Ack(in_ack[3]), .io_core_inputs_3_Data_flit(in_data[3*FLIT_W +: FLIT_W]),
    .io_core_inputs_4_HS_Req(in_req[4]), .io_core_inputs_4_HS_Ack(in_ack[4]), .io_core_inputs_4_Data_flit(in_data[4*FLIT_W +: FLIT_W]),
    .io_core_inputs_5_HS_Req(in_req[5]), .io_core_inputs_5_HS_Ack(in_ack[5]), .io_core_inputs_5_Data_flit(in_data[5*FLIT_W +: FLIT_W]),
    .io_core_inputs_6_HS_Req(in_req[6]), .io_core_inputs_6_HS_Ack(in_ack[6]), .io_core_inputs_6_Data_flit(in_data[6*FLIT_W +: FLIT_W]),
    .io_core_inputs_7_HS_Req(in_req[7]), .io_core_inputs_7_HS_Ack(in_ack[7]), .io_core_inputs_7_Data_flit(in_data[7*FLIT_W +: FLIT_W]),
    .io_core_inputs_8_HS_Req(in_req[8]), .io_core_inputs_8_HS_Ack(in_ack[8]), .io_core_inputs_8_Data_flit(in_data[8*FLIT_W +: FLIT_W]),
    .io_core_inputs_9_HS_Req(in_req[9]), .io_core_inputs_9_HS_Ack(in_ack[9]), .io_core_inputs_9_Data_flit(in_data[9*FLIT_W +: FLIT_W]),
    .io_core_inputs_10_HS_Req(in_req[10]), .io_core_inputs_10_HS_Ack(in_ack[10]), .io_core_inputs_10_Data_flit(in_data[10*FLIT_W +: FLIT_W]),
    .io_core_inputs_11_HS_Req(in_req[11]), .io_core_inputs_11_HS_Ack(in_ack[11]), .io_core_inputs_11_Data_flit(in_data[11*FLIT_W +: FLIT_W]),
    .io_core_inputs_12_HS_Req(in_req[12]), .io_core_inputs_12_HS_Ack(in_ack[12]), .io_core_inputs_12_Data_flit(in_data[12*FLIT_W +: FLIT_W]),
    .io_core_inputs_13_HS_Req(in_req[13]), .io_core_inputs_13_HS_Ack(in_ack[13]), .io_core_inputs_13_Data_flit(in_data[13*FLIT_W +: FLIT_W]),
    .io_core_inputs_14_HS_Req(in_req[14]), .io_core_inputs_14_HS_Ack(in_ack[14]), .io_core_inputs_14_Data_flit(in_data[14*FLIT_W +: FLIT_W]),
    .io_core_inputs_15_HS_Req(in_req[15]), .io_core_inputs_15_HS_Ack(in_ack[15]), .io_core_inputs_15_Data_flit(in_data[15*FLIT_W +: FLIT_W]),
    .io_top_input_0_HS_Req(in_req[16]), .io_top_input_0_HS_Ack(in_ack[16]), .io_top_input_0_Data_flit(in_data[16*FLIT_W +: FLIT_W]),
    .io_top_input_1_HS_Req(in_req[17]), .io_top_input_1_HS_Ack(in_ack[17]), .io_top_input_1_Data_flit(in_data[17*FLIT_W +: FLIT_W]),
    .io_core_outputs_0_HS_Req(out_req[0]), .io_core_outputs_0_HS_Ack(out_ack[0]), .io_core_outputs_0_Data_flit(out_data[0*FLIT_W +: FLIT_W]),
    .io_core_outputs_1_HS_Req(out_req[1]), .io_core_outputs_1_HS_Ack(out_ack[1]), .io_core_outputs_1_Data_flit(out_data[1*FLIT_W +: FLIT_W]),
    .io_core_outputs_2_HS_Req(out_req[2]), .io_core_outputs_2_HS_Ack(out_ack[2]), .io_core_outputs_2_Data_flit(out_data[2*FLIT_W +: FLIT_W]),
    .io_core_outputs_3_HS_Req(out_req[3]), .io_core_outputs_3_HS_Ack(out_ack[3]), .io_core_outputs_3_Data_flit(out_data[3*FLIT_W +: FLIT_W]),
    .io_core_outputs_4_HS_Req(out_req[4]), .io_core_outputs_4_HS_Ack(out_ack[4]), .io_core_outputs_4_Data_flit(out_data[4*FLIT_W +: FLIT_W]),
    .io_core_outputs_5_HS_Req(out_req[5]), .io_core_outputs_5_HS_Ack(out_ack[5]), .io_core_outputs_5_Data_flit(out_data[5*FLIT_W +: FLIT_W]),
    .io_core_outputs_6_HS_Req(out_req[6]), .io_core_outputs_6_HS_Ack(out_ack[6]), .io_core_outputs_6_Data_flit(out_data[6*FLIT_W +: FLIT_W]),
    .io_core_outputs_7_HS_Req(out_req[7]), .io_core_outputs_7_HS_Ack(out_ack[7]), .io_core_outputs_7_Data_flit(out_data[7*FLIT_W +: FLIT_W]),
    .io_core_outputs_8_HS_Req(out_req[8]), .io_core_outputs_8_HS_Ack(out_ack[8]), .io_core_outputs_8_Data_flit(out_data[8*FLIT_W +: FLIT_W]),
    .io_core_outputs_9_HS_Req(out_req[9]), .io_core_outputs_9_HS_Ack(out_ack[9]), .io_core_outputs_9_Data_flit(out_data[9*FLIT_W +: FLIT_W]),
    .io_core_outputs_10_HS_Req(out_req[10]), .io_core_outputs_10_HS_Ack(out_ack[10]), .io_core_outputs_10_Data_flit(out_data[10*FLIT_W +: FLIT_W]),
    .io_core_outputs_11_HS_Req(out_req[11]), .io_core_outputs_11_HS_Ack(out_ack[11]), .io_core_outputs_11_Data_flit(out_data[11*FLIT_W +: FLIT_W]),
    .io_core_outputs_12_HS_Req(out_req[12]), .io_core_outputs_12_HS_Ack(out_ack[12]), .io_core_outputs_12_Data_flit(out_data[12*FLIT_W +: FLIT_W]),
    .io_core_outputs_13_HS_Req(out_req[13]), .io_core_outputs_13_HS_Ack(out_ack[13]), .io_core_outputs_13_Data_flit(out_data[13*FLIT_W +: FLIT_W]),
    .io_core_outputs_14_HS_Req(out_req[14]), .io_core_outputs_14_HS_Ack(out_ack[14]), .io_core_outputs_14_Data_flit(out_data[14*FLIT_W +: FLIT_W]),
    .io_core_outputs_15_HS_Req(out_req[15]), .io_core_outputs_15_HS_Ack(out_ack[15]), .io_core_outputs_15_Data_flit(out_data[15*FLIT_W +: FLIT_W]),
    .io_top_output_0_HS_Req(out_req[16]), .io_top_output_0_HS_Ack(out_ack[16]), .io_top_output_0_Data_flit(out_data[16*FLIT_W +: FLIT_W]),
    .io_top_output_1_HS_Req(out_req[17]), .io_top_output_1_HS_Ack(out_ack[17]), .io_top_output_1_Data_flit(out_data[17*FLIT_W +: FLIT_W])
  );
endmodule

`default_nettype wire
