`timescale 1ns/1ps
`default_nettype none

// Packed handshake adapter for CMRTopMesh 2x2. Generated by
// sim/AsyncNoC/testbench/gen_topmesh2_port_adapter.py.

module async_topmesh2_port_adapter #(
  parameter integer FLIT_W = 28,
  parameter integer NUM_PORTS = 8
) (
  input  wire                      reset,
  input  wire [NUM_PORTS-1:0]      in_req,
  output wire [NUM_PORTS-1:0]      in_ack,
  input  wire [NUM_PORTS*FLIT_W-1:0] in_data,
  output wire [NUM_PORTS-1:0]      out_req,
  input  wire [NUM_PORTS-1:0]      out_ack,
  output wire [NUM_PORTS*FLIT_W-1:0] out_data
);
  wire unused_clock = 1'b0;
  CMRTopMesh dut (
    .clock(unused_clock), .reset(reset),
    .io_local_inputs_0_0_HS_Req(in_req[0]), .io_local_inputs_0_0_HS_Ack(in_ack[0]), .io_local_inputs_0_0_Data_flit(in_data[0*FLIT_W +: FLIT_W]),
    .io_local_inputs_0_1_HS_Req(in_req[1]), .io_local_inputs_0_1_HS_Ack(in_ack[1]), .io_local_inputs_0_1_Data_flit(in_data[1*FLIT_W +: FLIT_W]),
    .io_local_inputs_1_0_HS_Req(in_req[2]), .io_local_inputs_1_0_HS_Ack(in_ack[2]), .io_local_inputs_1_0_Data_flit(in_data[2*FLIT_W +: FLIT_W]),
    .io_local_inputs_1_1_HS_Req(in_req[3]), .io_local_inputs_1_1_HS_Ack(in_ack[3]), .io_local_inputs_1_1_Data_flit(in_data[3*FLIT_W +: FLIT_W]),
    .io_local_inputs_2_0_HS_Req(in_req[4]), .io_local_inputs_2_0_HS_Ack(in_ack[4]), .io_local_inputs_2_0_Data_flit(in_data[4*FLIT_W +: FLIT_W]),
    .io_local_inputs_2_1_HS_Req(in_req[5]), .io_local_inputs_2_1_HS_Ack(in_ack[5]), .io_local_inputs_2_1_Data_flit(in_data[5*FLIT_W +: FLIT_W]),
    .io_local_inputs_3_0_HS_Req(in_req[6]), .io_local_inputs_3_0_HS_Ack(in_ack[6]), .io_local_inputs_3_0_Data_flit(in_data[6*FLIT_W +: FLIT_W]),
    .io_local_inputs_3_1_HS_Req(in_req[7]), .io_local_inputs_3_1_HS_Ack(in_ack[7]), .io_local_inputs_3_1_Data_flit(in_data[7*FLIT_W +: FLIT_W]),
    .io_local_outputs_0_0_HS_Req(out_req[0]), .io_local_outputs_0_0_HS_Ack(out_ack[0]), .io_local_outputs_0_0_Data_flit(out_data[0*FLIT_W +: FLIT_W]),
    .io_local_outputs_0_1_HS_Req(out_req[1]), .io_local_outputs_0_1_HS_Ack(out_ack[1]), .io_local_outputs_0_1_Data_flit(out_data[1*FLIT_W +: FLIT_W]),
    .io_local_outputs_1_0_HS_Req(out_req[2]), .io_local_outputs_1_0_HS_Ack(out_ack[2]), .io_local_outputs_1_0_Data_flit(out_data[2*FLIT_W +: FLIT_W]),
    .io_local_outputs_1_1_HS_Req(out_req[3]), .io_local_outputs_1_1_HS_Ack(out_ack[3]), .io_local_outputs_1_1_Data_flit(out_data[3*FLIT_W +: FLIT_W]),
    .io_local_outputs_2_0_HS_Req(out_req[4]), .io_local_outputs_2_0_HS_Ack(out_ack[4]), .io_local_outputs_2_0_Data_flit(out_data[4*FLIT_W +: FLIT_W]),
    .io_local_outputs_2_1_HS_Req(out_req[5]), .io_local_outputs_2_1_HS_Ack(out_ack[5]), .io_local_outputs_2_1_Data_flit(out_data[5*FLIT_W +: FLIT_W]),
    .io_local_outputs_3_0_HS_Req(out_req[6]), .io_local_outputs_3_0_HS_Ack(out_ack[6]), .io_local_outputs_3_0_Data_flit(out_data[6*FLIT_W +: FLIT_W]),
    .io_local_outputs_3_1_HS_Req(out_req[7]), .io_local_outputs_3_1_HS_Ack(out_ack[7]), .io_local_outputs_3_1_Data_flit(out_data[7*FLIT_W +: FLIT_W])
  );
endmodule

`default_nettype wire
